# Generated by Django 4.2.7 on 2025-09-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('medical', 'Medical Terms'), ('symptoms', 'Symptoms'), ('ui', 'User Interface'), ('system', 'System Messages'), ('emergency', 'Emergency Messages')], default='system', max_length=15)),
                ('english_text', models.TextField()),
                ('luganda_text', models.TextField()),
                ('context', models.TextField(blank=True, help_text='Additional context for translators')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='language_tr_key_405402_idx'), models.Index(fields=['category'], name='language_tr_categor_f8d3d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalTermsGlossary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('anatomy', 'Anatomy'), ('symptoms', 'Symptoms'), ('diseases', 'Diseases'), ('treatments', 'Treatments'), ('medications', 'Medications'), ('procedures', 'Procedures'), ('emergency', 'Emergency Terms')], max_length=15)),
                ('english_term', models.CharField(max_length=200)),
                ('english_definition', models.TextField()),
                ('english_pronunciation', models.CharField(blank=True, max_length=300)),
                ('luganda_term', models.CharField(max_length=200)),
                ('luganda_definition', models.TextField()),
                ('luganda_pronunciation', models.CharField(blank=True, max_length=300)),
                ('english_synonyms', models.TextField(blank=True, help_text='Comma-separated synonyms')),
                ('luganda_synonyms', models.TextField(blank=True, help_text='Comma-separated synonyms')),
                ('usage_context', models.TextField(blank=True)),
                ('severity_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('english_audio', models.FileField(blank=True, null=True, upload_to='glossary/audio/en/')),
                ('luganda_audio', models.FileField(blank=True, null=True, upload_to='glossary/audio/lg/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['english_term'], name='language_me_english_542e23_idx'), models.Index(fields=['luganda_term'], name='language_me_luganda_036209_idx'), models.Index(fields=['category'], name='language_me_categor_911a93_idx')],
                'unique_together': {('english_term', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LanguageDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_input', models.TextField()),
                ('detected_language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('mixed', 'Mixed Languages'), ('unknown', 'Unknown')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('detection_method', models.CharField(default='auto', max_length=50)),
                ('user_confirmed_language', models.CharField(blank=True, choices=[('en', 'English'), ('lg', 'Luganda'), ('mixed', 'Mixed Languages'), ('unknown', 'Unknown')], max_length=10)),
                ('is_correct_detection', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['detected_language'], name='language_la_detecte_9c66a4_idx'), models.Index(fields=['confidence_score'], name='language_la_confide_9e115c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_type', models.CharField(choices=[('stt', 'Speech to Text'), ('tts', 'Text to Speech')], max_length=3)),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda')], max_length=2)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='audio/input/')),
                ('input_text', models.TextField(blank=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='audio/output/')),
                ('output_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=50)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'processing_type'], name='language_au_user_id_71e314_idx'), models.Index(fields=['status'], name='language_au_status_3cac4f_idx')],
            },
        ),
    ]
