# Generated by Django 4.2.7 on 2025-09-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('consultation', 'Consultation Record'), ('prescription', 'Prescription'), ('test_result', 'Test Result'), ('vaccine', 'Vaccination Record'), ('allergy', 'Allergy Information'), ('emergency', 'Emergency Treatment')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='records/documents/')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='records/images/')),
                ('record_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('is_on_blockchain', models.BooleanField(default=False)),
                ('provider_name', models.CharField(blank=True, max_length=200)),
                ('provider_license', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('view', 'View Record'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('blockchain_store', 'Store on Blockchain')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('parish', models.CharField(blank=True, max_length=100)),
                ('subcounty', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies separated by commas')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic medical conditions')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda')], default='en', max_length=2)),
                ('profile_hash', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'record_type'], name='records_med_patient_9eada4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['record_hash'], name='records_med_record__809956_idx'),
        ),
    ]
