# Generated by Django 4.2.7 on 2025-09-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('medical_record', 'Medical Record Storage'), ('medicine_verification', 'Medicine Verification'), ('patient_consent', 'Patient Consent'), ('access_grant', 'Access Grant')], max_length=30)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(max_length=42)),
                ('data_hash', models.CharField(max_length=64)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('medical_records', 'Medical Records Contract'), ('medicine_auth', 'Medicine Authentication Contract'), ('patient_consent', 'Patient Consent Contract')], max_length=20)),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('network', models.CharField(choices=[('ethereum_mainnet', 'Ethereum Mainnet'), ('ethereum_sepolia', 'Ethereum Sepolia Testnet'), ('polygon_mainnet', 'Polygon Mainnet'), ('polygon_mumbai', 'Polygon Mumbai Testnet')], max_length=20)),
                ('abi', models.JSONField()),
                ('bytecode', models.TextField()),
                ('deployment_transaction', models.CharField(max_length=66)),
                ('deployed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
            ],
            options={
                'unique_together': {('contract_type', 'network')},
            },
        ),
        migrations.CreateModel(
            name='PatientConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data_storage', 'Data Storage on Blockchain'), ('data_sharing', 'Data Sharing with Healthcare Providers'), ('research', 'Research Participation'), ('emergency_access', 'Emergency Access')], max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('consent_text', models.TextField()),
                ('digital_signature', models.CharField(blank=True, max_length=200)),
                ('consent_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('blockchain_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.blockchaintransaction')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('qr_code', models.CharField(max_length=500, unique=True)),
                ('verification_status', models.CharField(choices=[('authentic', 'Authentic'), ('counterfeit', 'Counterfeit'), ('unknown', 'Unknown'), ('pending', 'Pending Verification')], default='pending', max_length=15)),
                ('blockchain_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.blockchaintransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_697a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['data_hash'], name='blockchain__data_ha_8df7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['status'], name='blockchain__status_096a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientconsentrecord',
            index=models.Index(fields=['patient', 'consent_type'], name='blockchain__patient_8f2d18_idx'),
        ),
        migrations.AddIndex(
            model_name='patientconsentrecord',
            index=models.Index(fields=['consent_hash'], name='blockchain__consent_2be33d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientconsentrecord',
            unique_together={('patient', 'consent_type')},
        ),
        migrations.AddIndex(
            model_name='medicineverification',
            index=models.Index(fields=['qr_code'], name='blockchain__qr_code_bf7cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineverification',
            index=models.Index(fields=['batch_number'], name='blockchain__batch_n_7b2ba9_idx'),
        ),
    ]
